<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'mwGearman\GearmanClientAware' => __DIR__ . '/src/mwGearman/GearmanClientAware.php',
    'mwGearman\Worker\Pecl'        => __DIR__ . '/src/mwGearman/Worker/Pecl.php',
    'mwGearman\Client\Pecl'        => __DIR__ . '/src/mwGearman/Client/Pecl.php',
    'mwGearman\Task'               => __DIR__ . '/src/mwGearman/Task.php',
    'mwGearman\Client'             => __DIR__ . '/src/mwGearman/Client.php',
    'mwGearman\Worker'             => __DIR__ . '/src/mwGearman/Worker.php',
    'mwGearman\Task\Task'          => __DIR__ . '/src/mwGearman/Task/Task.php',
    'mwGearman\GearmanWorkerAware' => __DIR__ . '/src/mwGearman/GearmanWorkerAware.php',
    'mwGearman\Module'             => __DIR__ . '/Module.php',
);