<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'mwGearman\Job\AbstractJob'                    => __DIR__ . '/src/mwGearman/Job/AbstractJob.php',
    'mwGearman\Job\Pecl'                           => __DIR__ . '/src/mwGearman/Job/Pecl.php',
    'mwGearman\Exception'                          => __DIR__ . '/src/mwGearman/Exception.php',
    'mwGearman\Exception\InvalidArgumentException' => __DIR__ . '/src/mwGearman/Exception/InvalidArgumentException.php',
    'mwGearman\Exception\RuntimeException'         => __DIR__ . '/src/mwGearman/Exception/RuntimeException.php',
    'mwGearman\Exception\DomainException'          => __DIR__ . '/src/mwGearman/Exception/DomainException.php',
    'mwGearman\Worker\Pecl'                        => __DIR__ . '/src/mwGearman/Worker/Pecl.php',
    'mwGearman\Client\Pecl'                        => __DIR__ . '/src/mwGearman/Client/Pecl.php',
    'mwGearman\Connection\AbstractPecl'            => __DIR__ . '/src/mwGearman/Connection/AbstractPecl.php',
    'mwGearman\ClientInterface'                    => __DIR__ . '/src/mwGearman/ClientInterface.php',
    'mwGearman\TaskInterface'                      => __DIR__ . '/src/mwGearman/TaskInterface.php',
    'mwGearman\ConnectionInterface'                => __DIR__ . '/src/mwGearman/ConnectionInterface.php',
    'mwGearman\Task\Task'                          => __DIR__ . '/src/mwGearman/Task/Task.php',
    'mwGearman\JobInterface'                       => __DIR__ . '/src/mwGearman/JobInterface.php',
    'mwGearman\WorkerInterface'                    => __DIR__ . '/src/mwGearman/WorkerInterface.php',
    'mwGearman\Module'                             => __DIR__ . '/Module.php',
);