<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    '\mwGearman\Client\Pecl' => __DIR__ . '/src/mwGearman/Client/Pecl.php',
    '\mwGearman\Task'        => __DIR__ . '/src/mwGearman/Task.php',
    '\mwGearman\Client'      => __DIR__ . '/src/mwGearman/Client.php',
    '\mwGearman\Task\Task'   => __DIR__ . '/src/mwGearman/Task/Task.php',
    'mwGearman\Module'       => __DIR__ . '/Module.php',
);